import type { TokenEntry } from './types';

// critical token ->  ESI 2 
export const CRITICAL_TOKENS: TokenEntry[] = [
  {
    id: 'SYM_CHEST_PAIN_TYPICAL',
    description_ro: 'Durere toracică compresivă, iradiere braț/mandibulă',
    description_en: 'Compressive chest pain radiating to arm or jaw',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_BREATHING_DIFFICULTY',
    description_ro: 'Dispnee severă, sub-Level 1',
    description_en: 'Severe breathing difficulty, below Level 1 threshold',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_NEURO_DEFICIT',
    description_ro: 'Deficit neurologic focal brusc (față strâmbă, vorbire afectată, slăbiciune unilaterală)',
    description_en: 'Sudden focal neurological deficit (facial droop, speech, unilateral weakness)',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_HEADACHE_SEVERE',
    description_ro: 'Cea mai mare durere de cap din viață, debut brusc',
    description_en: 'Worst headache of life, sudden onset',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_VISION_LOSS',
    description_ro: 'Pierdere totală sau parțială a vederii, debut brusc',
    description_en: 'Sudden total or partial vision loss',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_TESTICULAR_PAIN',
    description_ro: 'Durere scrotală intensă, debut brusc (risc torsiune)',
    description_en: 'Severe scrotal pain, sudden onset (testicular torsion risk)',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_TRAUMA_HIGH_KINETIC',
    description_ro: 'Mecanism sever: cădere >6m, ejectat din vehicul, accident rutier major',
    description_en: 'High-kinetic mechanism: fall >20ft, ejected from vehicle, major MVA',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_TOXIC_INGESTION',
    description_ro: 'Supradoză medicamente sau ingestie substanță chimică',
    description_en: 'Medication overdose or chemical ingestion',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_EYE_CHEM',
    description_ro: 'Substanță chimică în ochi (acid, bază, clor)',
    description_en: 'Chemical substance in the eye (acid, alkali, chlorine)',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
  {
    id: 'SYM_VAGINAL_BLEEDING_PREG',
    description_ro: 'Sângerare vaginală la pacienta gravidă',
    description_en: 'Vaginal bleeding in a pregnant patient',
    is_critical: true,
    base_resources: 0,
    resource_types: [],
    context_modifiers: [],
  },
];
